// <auto-generated />
using System;
using API_WebBDDHT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_WebBDDHT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615152538_AddAvatarToTaiKhoan")]
    partial class AddAvatarToTaiKhoan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_WebBDDHT.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<int>("MaSP")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DonGia");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("MaDH", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietDonHang");

                    b.HasData(
                        new
                        {
                            MaDH = 1,
                            MaSP = 2,
                            DonGia = 25000m,
                            SoLuong = 1
                        },
                        new
                        {
                            MaDH = 1,
                            MaSP = 4,
                            DonGia = 650000m,
                            SoLuong = 1
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaGH")
                        .HasColumnType("int")
                        .HasColumnName("MaGH");

                    b.Property<int>("MaSP")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DonGia");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("MaGH", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietGioHang");

                    b.HasData(
                        new
                        {
                            MaGH = 1,
                            MaSP = 1,
                            DonGia = 4000m,
                            SoLuong = 1
                        },
                        new
                        {
                            MaGH = 1,
                            MaSP = 2,
                            DonGia = 25000m,
                            SoLuong = 1
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.ChiTietNhapHang", b =>
                {
                    b.Property<int>("MaNH")
                        .HasColumnType("int")
                        .HasColumnName("MaNH");

                    b.Property<int>("MaSP")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DonGia");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("MaNH", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietNhapHang");

                    b.HasData(
                        new
                        {
                            MaNH = 1,
                            MaSP = 3,
                            DonGia = 300000m,
                            SoLuong = 30
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.DanhGia", b =>
                {
                    b.Property<int>("MaDG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDG"));

                    b.Property<int>("MaDH")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaSP")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<DateTime?>("NgayDG")
                        .HasColumnType("date")
                        .HasColumnName("NgayDG");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int")
                        .HasColumnName("SoSao");

                    b.HasKey("MaDG");

                    b.HasIndex("MaDH");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaSP");

                    b.ToTable("DanhGia");

                    b.HasData(
                        new
                        {
                            MaDG = 1,
                            MaDH = 1,
                            MaKH = 1,
                            MaSP = 4,
                            NgayDG = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Máy tính chính hãng, giao nhanh, đóng gói cẩn thận. Rất hài lòng!",
                            SoSao = 5
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.DonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDH"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChiGiaoHang");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTenNguoiNhan");

                    b.Property<string>("MaGiaoDichNgoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaGiaoDịchNgoai");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaPTTT")
                        .HasColumnType("int")
                        .HasColumnName("MaPTTT");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("date")
                        .HasColumnName("NgayDat");

                    b.Property<string>("SDTNguoiNhan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDTNguoiNhan");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa thanh toán")
                        .HasColumnName("TrangThaiThanhToan");

                    b.HasKey("MaDH");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaPTTT");

                    b.ToTable("DonHang");

                    b.HasData(
                        new
                        {
                            MaDH = 1,
                            DiaChiGiaoHang = "123 Nguyễn Trãi, Quận 5, HCM",
                            GhiChu = "Giao giờ hành chính",
                            HoTenNguoiNhan = "Nguyễn Thúy Lan",
                            MaGiaoDichNgoai = "VNPAY12345",
                            MaKH = 1,
                            MaPTTT = 3,
                            NgayDat = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDTNguoiNhan = "0901234567",
                            TongTien = 675000m,
                            TrangThai = "Đang giao",
                            TrangThaiThanhToan = "Đã thanh toán"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.GioHang", b =>
                {
                    b.Property<int>("MaGH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGH"));

                    b.Property<string>("CartToken")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CartToken");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("date")
                        .HasColumnName("NgayCapNhat");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TongTien");

                    b.HasKey("MaGH");

                    b.HasIndex("MaKH");

                    b.ToTable("GioHang");

                    b.HasData(
                        new
                        {
                            MaGH = 1,
                            MaKH = 1,
                            NgayCapNhat = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 29000m
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.HangKhachHang", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<int>("DiemToiThieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("DiemToiThieu");

                    b.Property<int>("PhanTramUuDai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("PhanTramUuDai");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenHang");

                    b.HasKey("MaHang");

                    b.ToTable("HangKhachHang");

                    b.HasData(
                        new
                        {
                            MaHang = 1,
                            DiemToiThieu = 0,
                            PhanTramUuDai = 0,
                            TenHang = "Đồng"
                        },
                        new
                        {
                            MaHang = 2,
                            DiemToiThieu = 100,
                            PhanTramUuDai = 2,
                            TenHang = "Bạc"
                        },
                        new
                        {
                            MaHang = 3,
                            DiemToiThieu = 500,
                            PhanTramUuDai = 5,
                            TenHang = "Vàng"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<int>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("DiemTichLuy");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<int?>("MaHang")
                        .HasColumnType("int")
                        .HasColumnName("MaHang");

                    b.Property<int?>("MaTK")
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaKH");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            DiaChi = "123 Nguyễn Trãi, Quận 5, HCM",
                            DiemTichLuy = 150,
                            HoTen = "Nguyễn Thúy Lan",
                            MaHang = 2,
                            MaTK = 3,
                            SDT = "0901234567"
                        },
                        new
                        {
                            MaKH = 2,
                            DiaChi = "456 Lê Lợi, Quận 1, HCM",
                            DiemTichLuy = 20,
                            HoTen = "Trần Hoàng Nam",
                            MaHang = 1,
                            MaTK = 4,
                            SDT = "0918889999"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("MaKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKM"));

                    b.Property<string>("DieuKienApDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DieuKienApDung");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("NgayBatDau");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("NgayKetThuc");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int")
                        .HasColumnName("PhanTramGiam");

                    b.Property<string>("TenKM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKM");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMai");

                    b.HasData(
                        new
                        {
                            MaKM = 1,
                            DieuKienApDung = "Áp dụng cho các dòng bút viết và tập vở",
                            NgayBatDau = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 10,
                            TenKM = "Chào Hè Rực Rỡ"
                        },
                        new
                        {
                            MaKM = 2,
                            DieuKienApDung = "Giảm giá sâu máy tính học sinh",
                            NgayBatDau = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 15,
                            TenKM = "Mùa Tựu Trường"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.LoaiSP", b =>
                {
                    b.Property<int>("MaLoaiSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLoaiSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiSP"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenLoai");

                    b.HasKey("MaLoaiSP");

                    b.ToTable("LoaiSP");

                    b.HasData(
                        new
                        {
                            MaLoaiSP = 1,
                            MoTa = "Các loại bút bi, bút chì, bút dạ quang, bút ký cao cấp",
                            TenLoai = "Bút - Viết"
                        },
                        new
                        {
                            MaLoaiSP = 2,
                            MoTa = "Sổ tay lò xo, tập học sinh, sổ văn phòng",
                            TenLoai = "Sổ - Tập - Vở"
                        },
                        new
                        {
                            MaLoaiSP = 3,
                            MoTa = "Giấy in A4, giấy note, giấy bìa màu",
                            TenLoai = "Giấy các loại"
                        },
                        new
                        {
                            MaLoaiSP = 4,
                            MoTa = "Máy tính Casio, thước kẻ, gôm, kéo văn phòng",
                            TenLoai = "Dụng cụ học tập & Máy tính"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("MaNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNCC"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");

                    b.HasData(
                        new
                        {
                            MaNCC = 1,
                            DiaChi = "KCN Tân Tạo, Bình Tân, HCM",
                            Email = "info@thienlong.vn",
                            SDT = "02837505555",
                            TenNCC = "Công ty CP Tập đoàn Thiên Long"
                        },
                        new
                        {
                            MaNCC = 2,
                            DiaChi = "Phường 10, Quận Gò Vấp, HCM",
                            Email = "toancauvpp@gmail.com",
                            SDT = "0944555666",
                            TenNCC = "Nhà phân phối Văn Phòng Phẩm Toàn Cầu"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<string>("MaSoNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaSoNhanVien");

                    b.Property<int?>("MaTK")
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaNV");

                    b.HasIndex("MaSoNhanVien")
                        .IsUnique();

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            DiaChi = "789 Cách Mạng Tháng 8, Tân Bình, HCM",
                            GioiTinh = "Nam",
                            HoTen = "Lê Văn Dũng",
                            MaSoNhanVien = "NV001",
                            MaTK = 2,
                            NgaySinh = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0987654321"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.NhapHang", b =>
                {
                    b.Property<int>("MaNH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNH"));

                    b.Property<int?>("MaNCC")
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("date")
                        .HasColumnName("NgayNhap");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaNH");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("NhapHang");

                    b.HasData(
                        new
                        {
                            MaNH = 1,
                            MaNCC = 2,
                            MaNV = 1,
                            NgayNhap = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 10000000m,
                            TrangThai = "Đã hoàn thành"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("MaPTTT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPTTT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPTTT"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MaCode");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenPhuongThuc");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("TrangThai");

                    b.HasKey("MaPTTT");

                    b.HasIndex("MaCode")
                        .IsUnique();

                    b.ToTable("PhuongThucThanhToan");

                    b.HasData(
                        new
                        {
                            MaPTTT = 1,
                            GhiChu = "Khách hàng trả tiền mặt cho shipper",
                            HinhAnh = "cod.png",
                            MaCode = "COD",
                            TenPhuongThuc = "Thanh toán khi nhận hàng (COD)",
                            TrangThai = true
                        },
                        new
                        {
                            MaPTTT = 2,
                            GhiChu = "Quét mã chuyển khoản",
                            HinhAnh = "momo.png",
                            MaCode = "MOMO",
                            TenPhuongThuc = "Ví điện tử MoMo",
                            TrangThai = true
                        },
                        new
                        {
                            MaPTTT = 3,
                            GhiChu = "Thanh toán qua ngân hàng nội địa hoặc QR",
                            HinhAnh = "vnpay.png",
                            MaCode = "VNPAY",
                            TenPhuongThuc = "Cổng thanh toán VNPAY",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.SanPham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("Gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HinhAnh");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int")
                        .HasColumnName("MaLoai");

                    b.Property<int?>("MaNCC")
                        .HasColumnType("int")
                        .HasColumnName("MaNCC");

                    b.Property<int?>("MaTH")
                        .HasColumnType("int")
                        .HasColumnName("MaTH");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongTon");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSP");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaTH");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            MaSP = 1,
                            Gia = 4000m,
                            HinhAnh = "tl027.jpg",
                            MaLoai = 1,
                            MaNCC = 1,
                            MaTH = 1,
                            MoTa = "Bút bi bấm truyền thống, mực đều, nét chữ đẹp",
                            SoLuongTon = 500,
                            TenSP = "Bút Bi Thiên Long TL-027"
                        },
                        new
                        {
                            MaSP = 2,
                            Gia = 25000m,
                            HinhAnh = "so_campus_a5.jpg",
                            MaLoai = 2,
                            MaNCC = 2,
                            MaTH = 4,
                            MoTa = "Giấy chống lóa mắt, lò xo kép chắc chắn",
                            SoLuongTon = 150,
                            TenSP = "Sổ lò xo Campus A5 160 trang"
                        },
                        new
                        {
                            MaSP = 3,
                            Gia = 345000m,
                            HinhAnh = "giay_double_a.jpg",
                            MaLoai = 3,
                            MaNCC = 2,
                            MaTH = 3,
                            MoTa = "Giấy in văn phòng trắng đẹp, không kẹt giấy (5 ram/thùng)",
                            SoLuongTon = 80,
                            TenSP = "Thùng Giấy Double A A4 70gsm"
                        },
                        new
                        {
                            MaSP = 4,
                            Gia = 650000m,
                            HinhAnh = "casio_580vnx.jpg",
                            MaLoai = 4,
                            MaNCC = 2,
                            MaTH = 2,
                            MoTa = "Hỗ trợ 521 tính năng, ngôn ngữ tiếng Việt cho học sinh, sinh viên",
                            SoLuongTon = 50,
                            TenSP = "Máy tính khoa học Casio FX-580VN X"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Avatar");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenDangNhap");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("TrangThai");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VaiTro");

                    b.HasKey("MaTK");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            MaTK = 1,
                            Email = "admin@vpp.com",
                            MatKhau = "hashed_password_1",
                            TenDangNhap = "admin",
                            TrangThai = true,
                            VaiTro = "Quản trị viên"
                        },
                        new
                        {
                            MaTK = 2,
                            Email = "dung@vpp.com",
                            MatKhau = "hashed_password_2",
                            TenDangNhap = "nv_dung",
                            TrangThai = true,
                            VaiTro = "Nhân viên"
                        },
                        new
                        {
                            MaTK = 3,
                            Email = "lan@gmail.com",
                            MatKhau = "hashed_password_3",
                            TenDangNhap = "kh_lan",
                            TrangThai = true,
                            VaiTro = "Khách hàng"
                        },
                        new
                        {
                            MaTK = 4,
                            Email = "nam@gmail.com",
                            MatKhau = "hashed_password_4",
                            TenDangNhap = "kh_nam",
                            TrangThai = true,
                            VaiTro = "Khách hàng"
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.ThuongHieu", b =>
                {
                    b.Property<int>("MaTH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTH"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QuocGia");

                    b.Property<string>("TenTH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTH");

                    b.HasKey("MaTH");

                    b.ToTable("ThuongHieu");

                    b.HasData(
                        new
                        {
                            MaTH = 1,
                            MoTa = "Thương hiệu văn phòng phẩm quốc dân",
                            QuocGia = "Việt Nam",
                            TenTH = "Thiên Long"
                        },
                        new
                        {
                            MaTH = 2,
                            MoTa = "Thương hiệu máy tính bỏ túi hàng đầu thế giới",
                            QuocGia = "Nhật Bản",
                            TenTH = "Casio"
                        },
                        new
                        {
                            MaTH = 3,
                            MoTa = "Thương hiệu giấy in cao cấp",
                            QuocGia = "Thái Lan",
                            TenTH = "Double A"
                        },
                        new
                        {
                            MaTH = 4,
                            MoTa = "Chuyên các dòng tập, sổ tay chất lượng cao",
                            QuocGia = "Nhật Bản",
                            TenTH = "Campus"
                        });
                });

            modelBuilder.Entity("sp_km", b =>
                {
                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("MaKM")
                        .HasColumnType("int");

                    b.HasKey("MaSP", "MaKM");

                    b.HasIndex("MaKM");

                    b.ToTable("sp_km");

                    b.HasData(
                        new
                        {
                            MaSP = 1,
                            MaKM = 1
                        },
                        new
                        {
                            MaSP = 2,
                            MaKM = 1
                        },
                        new
                        {
                            MaSP = 4,
                            MaKM = 2
                        });
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_WebBDDHT.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.ChiTietGioHang", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_WebBDDHT.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.ChiTietNhapHang", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.NhapHang", "NhapHang")
                        .WithMany("ChiTietNhapHangs")
                        .HasForeignKey("MaNH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_WebBDDHT.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhapHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.DanhGia", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.DonHang", "DonHang")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_WebBDDHT.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API_WebBDDHT.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonHang");

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.DonHang", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API_WebBDDHT.Entities.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaPTTT");

                    b.Navigation("KhachHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.GioHang", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.KhachHang", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.HangKhachHang", "HangKhachHang")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API_WebBDDHT.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("API_WebBDDHT.Entities.KhachHang", "MaTK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HangKhachHang");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.NhanVien", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("API_WebBDDHT.Entities.NhanVien", "MaTK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.NhapHang", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API_WebBDDHT.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.SanPham", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.LoaiSP", "LoaiSP")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API_WebBDDHT.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API_WebBDDHT.Entities.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaTH")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoaiSP");

                    b.Navigation("NhaCungCap");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("sp_km", b =>
                {
                    b.HasOne("API_WebBDDHT.Entities.KhuyenMai", null)
                        .WithMany()
                        .HasForeignKey("MaKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_WebBDDHT.Entities.SanPham", null)
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.HangKhachHang", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.LoaiSP", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.NhaCungCap", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.NhapHang", b =>
                {
                    b.Navigation("ChiTietNhapHangs");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("API_WebBDDHT.Entities.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
